# Generated by Django 4.1.1 on 2022-10-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_account_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
