# Generated by Django 4.0.2 on 2022-10-24 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_displaypage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisplayPage',
        ),
    ]
