# Generated by Django 4.0.2 on 2022-10-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_delete_displaypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
