# Generated by Django 4.0.2 on 2022-11-04 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_order_drink_order_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
