# Generated by Django 4.1.1 on 2022-11-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_delete_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ingredientsCount',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
