# Generated by Django 4.1.1 on 2022-11-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_order_ingredientscount_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderNum',
            field=models.IntegerField(default=0),
        ),
    ]
